# Generated by Django 5.2.7 on 2026-02-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='region',
            field=models.CharField(choices=[('DS', 'Dolnośląskie'), ('KP', 'Kujawsko-pomorskie'), ('LU', 'Lubelskie'), ('LB', 'Lubuskie'), ('LD', 'Łódzkie'), ('MA', 'Małopolskie'), ('MZ', 'Mazowieckie'), ('OP', 'Opolskie'), ('PK', 'Podkarpackie'), ('PD', 'Podlaskie'), ('PM', 'Pomorskie'), ('SL', 'Śląskie'), ('SK', 'Świętokrzyskie'), ('WN', 'Warmińsko-mazurskie'), ('WP', 'Wielkopolskie'), ('ZP', 'Zachodniopomorskie')], default='MZ', max_length=2),
            preserve_default=False,
        ),
    ]
